Added Universal wireless communication library
creatorsgarten/hacktoberfest-museum pull request #45
Opened 2022-10-30 11:01 UTC by siravijbb

**Always tag `🚀 READY FOR REVIEW` once your PR is Ready to be one of us :)**

We value your endeavors to enhance the Hacktoberfest Museum better!

## If (this.PR.category === "The new entry 💫")

**Please tag `The new entry 💫` to the PR in order to categorize yours as the star being recognized by the Museum.**

## Else if (this.PR.category === "Enhancement 🛠")

**Please tag `Enhancement 🛠` to the PR as you're developing the Museum more wonderfully!**

## Finally:

> 🪄 **DON'T FORGET TO CLAIM YOUR TICKET!** via [Eventpop application form.](https://www.eventpop.me/events/13854/application_forms/845/applicants/new)

2022-10-30 11:36 UTC, Gusb3ll requested changes
Did you do any [contribution](https://github.com/jgromes/RadioLib/graphs/contributors) to the project or has any relation to it?, If you wanted to continue then please format your code using `pnpm prettier:write` kub

2022-10-30 11:36 UTC, Gusb3ll commented
I think I've said before to check for formatting before pushing, please do it on your next PR kub

2022-10-30 13:02 UTC, siravijbb commented
> Did you do any [contribution](https://github.com/jgromes/RadioLib/graphs/contributors) to the project or has any relation to it?, If you wanted to continue then please format your code using `pnpm prettier:write` kub

eh,I open issue for them,But why `pnpm prettier:write` it said 'The filename, directory name, or volume label syntax is incorrect.'

2022-10-30 14:15 UTC, siravijbb commented
![image](https://user-images.githubusercontent.com/47503079/198883347-5bd7b44b-1e6c-4abf-bdc4-0e41f8013d3d.png)

2022-10-30 20:57 UTC, Gusb3ll commented
🤔

2022-10-31 15:15 UTC, Leomotors commented
My suggestion

https://learn.microsoft.com/en-us/windows/wsl/install

or

https://www.apple.com/th/mac/

2022-10-31 16:25 UTC, Leomotors requested changes

2022-10-31 16:25 UTC, Leomotors commented on src/entries/Universal-wireless-communication-library.ts
> +export default props;
No CRLF

2022-10-31 17:23 UTC, closed without merging